#!/usr/bin/env bash
# transfers a file over scp
if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE \
IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
if [ $# -gt 3 ];
then
	OPT_PLUS_PATH="-i $4"
	scp -o StrictHostKeyChecking=off "$OPT_PLUS_PATH"\
		"$PATH_TO_FILE" "scp://$USERNAME@$IP"
else
	scp -o StrictHostKeyChecking=off "$PATH_TO_FILE"\
		"scp://$USERNAME@$IP"
fi
