#!/usr/bin/env bash
# sets a permanent redirect to /redirect_me path
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me \
https:\/\/www.digitalocean.com\/community\/tutorials\/how-to-create-\
temporary-and-permanent-redirects-with-nginx permanent;/" /etc/nginx/\
sites-available/default

sudo service nginx restart
