#!/usr/bin/env bash
# lists file without part before -
list=$( ls )
for i in $list;
do
	IFS="-"
	read -ra ADDR <<< "$i"
	if [ "${ADDR[1]}" ]; then
		echo "${ADDR[1]}"
	else
		echo "${ADDR[0]}"
	fi
done
