#!/usr/bin/env bash
# script configures nginx to run as nginx
sudo pkill apache2
sudo service apache2 stop
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo service nginx restart
