#!/usr/bin/env bash
# script configures nginx to run as nginx
sudo pkill apache2
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
